R = 0.5 # promień kołowrotka (m)
M_w = 500 # masa pustej windy (tara masy windy) (kg)
M_pw = 750 # masa przeciwwagi (kg)
G = 9.81 # przyspieszenie ziemskie (m/s^2)
M_wir = 20 # masa wirnika (kg)
R_w = 10 # rezystancja zastępcza uzwojeń wirnika (Ω)
L_w = 10 # indukcyjność zastępcza uzwojeń wirnika (H)
k_e = 10 # stała elektryczna, zależna m.in. od strumienia magnetycznego stojana oraz liczby zwojów w uzwojeniach wirnika
k_m = 10 # stała mechaniczna, zależna m.in. od strumienia magnetycznego stojana oraz liczby zwojów w uzwojeń wirnika
T_p = 0.01 # czas próbkowania (s)
T_s = 20  # czas symulacji (s)