R = 1 # promień kołowrotka
M_w = 1 # masa pustej windy (tara masy windy)
M_pw = 1 # masa przeciwwagi
G = 1 # przyspieszenie ziemskie
M_wir = 1 # masa wirnika
R_w = 1 # rezystancja zastępcza uzwojeń wirnika
L_w = 1 # indukcyjność zastępcza uzwojeń wirnika
k_e = 1 # stała elektryczna, zależna m.in. od strumienia magnetycznego stojana oraz liczby zwojów w uzwojeniach wirnika
k_m = 1 # stała mechaniczna, zależna m.in. od strumienia magnetycznego stojana oraz liczby zwojów w uzwojeniach wirnika
B = 1 # współczynnik tarcia lepkiego zredukowany do wału wirnika
M_obc = 1 # stały moment obciążenia silnika
T_p = 1 # czas próbkowania

# N_w = 1  # siła naciągu liny pomiędzy wałem wirnika a windą
# N_p = 1 # siła naciągu liny pomiędzy wałem wirnika a przeciwwagą
# Q_w = 1 # ciężar windy
# Q_p = 1 # ciężar przeciwwagi
# M_obrw = 1 # moment obrotowy wirnika
# F_wypw = 1 # siła wypadkowa działająca na windę
# F_wypp = 1 # siła wypadkowa działająca na przeciwwagę
# M_wypw = 1 # moment wypadkowy działający na wirnik
# A = 1 # przyspieszenie układu
# I_bezw = 1 # moment bezwładności wirnika
# E = 1 # przyspieszenie kątowe wirnika
# I_w = 1 # prąd płynący w uzwojeniach wirnika
# I_wp = 1 # prąd płynący w uzwojeniach wirnika poprzedni
# V_0 = 1 # prędkość, którą miała winda przed rozpoczęciem nowego okresu czasu $T_p$
# H = 1 # wysokość aktualna windy

